github.com:
    users:
        kersar82-cell:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: kersar82-cell
